name: CI
on:
  push:
    branches-ignore:
      - main

jobs:
  integration:
    name: Integration Check
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.8'
          check-latest: true
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
      - name: npm install
        run: npm i
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier:check
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v1.0.9
        with:
          status: ${{ job.status }}
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
